package test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2016-03-06T17:19:42.992+05:30
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://ws.cdyne.com/", name = "IP2GeoHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface IP2GeoHttpPost {

    /**
     * Use a License Key of 0 for Testing
     */
    @WebResult(name = "IPInformation", targetNamespace = "http://ws.cdyne.com/", partName = "Body")
    @WebMethod(operationName = "ResolveIP")
    public IPInformation resolveIP(
        @WebParam(partName = "ipAddress", name = "ipAddress", targetNamespace = "")
        java.lang.String ipAddress,
        @WebParam(partName = "licenseKey", name = "licenseKey", targetNamespace = "")
        java.lang.String licenseKey
    );
}
